### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Cold-Stars** [KaleW515/fast-translate#3]
Traceback (most recent call last):
  File "/opt/fast-translate/./main.py", line 6, in <module>
    import container
  File "/opt/fast-translate/container.py", line 5, in <module>
    from core.config import configuration
  File "/opt/fast-translate/core/config/configuration.py", line 16, in <module>
    class Configuration:
  File "/opt/fast-translate/core/config/configuration.py", line 122, in Configuration
    def change_baidu_secret(self, appid: str, appkey: str):
TypeError: 'staticmethod' object is not callable

系统manjaro kde

**Comment by KaleW515** [comment]
已经修复

**Comment by Cold-Stars** [comment]
大佬效率好高
